### ISSUE TITLE
Configuration Parameter Mismatch for Workato Vendor API Key

### ISSUE THREAD

**Issue by JustinPaul-Workato** [workato/connection-embed-sample#9]
Within `index.js` the reference to the Workato Vendor API Token is named `WK_API_TOKEN`.  The `.env` file references this same parameter with a different name `WK_USER_TOKEN`.  These values should match. 

Suggestion is to update `.env` file to reference `WK_API_TOKEN` instead of `WK_USER_TOKEN`.  This would avoid a change to the documentation.

**Comment by JustinPaul-Workato** [comment]
@n0mid @phil-workato @graceliching @th0r 

I'm not able to create a PR for this.  Can someone please implement this simple fix?

**Comment by n0mid** [comment]
@JustinPaul-Workato  What is a different between `WK_API_KEY` and `WK_API_TOKEN` in this case? 
<img width="532" alt="image" src="https://github.com/workato/connection-embed-sample/assets/3842972/2df091df-d069-4c9c-a369-4576f20c01e6">

Also, I can't find using of `WK_API_TOKEN` in the application

**Comment by JustinPaul-Workato** [comment]
My apologies, let me clarify.  `WK_API_TOKEN` is used to call Embedded APIs whereas 'WK_API_KEY' is the Vendor Key that is generated from Workato backend when embedding configuration is applied.  Ideally, the `.env` file is as follows so that customers can easily configure with minimal guesswork:



#Workato origin
`VUE_APP_WK_ORIGIN=https://app.workato.com`

#App origin
`VUE_APP_WK_HOST=https://app.workato.com`

#Url to Workato Embedding Client Script
`VUE_APP_WK_OEM_CLIENT_URL=https://embedding.workato.com/r/embedding-client.js`

#Used to sign the JWT
`WK_JWT_PRIVATE_KEY=`

#Vendor Account ID
`WK_API_KEY=`

#End Customer Account ID
`WK_USER_ID=`

#Required in order to call Workato Embedded API endpoints
`WK_API_TOKEN=`

# Basic HTTP auth settings
# Leave these blank unless you want to enable login to the app
`USER_NAME=`
`USER_PASSWORD=`
